version: '3'

services:
  thermostat.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - connection-string=Server=sql.data;Database=Hqv.Thermostat;User Id=sa;Password=Pass@word
      - connection-string-master=Server=sql.data;Database=master;User Id=sa;Password=Pass@word
    ports:
      - "80"

  sql.data:    
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
