version: '3'

services:
  thermostat.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    volumes:
      - C:\DockerHome\HomeAutomation\ThermostatApi:/app/log
    ports:
      - "80"