version: '3'

services:
  thermostat.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging   
      - data:connection-string=Server=tcp:hgvdevhomeautomation.database.windows.net,1433;Initial Catalog=hqv-home-automation-dev;Persist Security Info=False;User ID=viet.hoang;Password=upupdown1!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
      - redis:connection-string=hqv-home-automation-dev.redis.cache.windows.net:6380,password=XLAKSjphITy2g5SD7k2Ukkbu5trPbdtQhls+W/FTZp0=,ssl=True,abortConnect=False
    volumes:
      - C:\DockerHome\HomeAutomation\ThermostatApi:/app/log
    ports:
      - 47001:80
    container_name: thermostat.api.staging